export const TUTOR_QUALIFICATIONS_LIST = [
  "B.Arch", "B.Com", "B.Ed", "B.LLB", "B.Lib", "B.Ped", "B.Pharma", "B.Sc", "B.Tech", "BA", "BBA", "BBM", "BCA", "BDS", "BFA", "BHM", "BJ", "BPT", "CA", "CFA", "CS", "D.Ed", "D.El.Ed", "DM", "DNB", "Ed.D.", "ICWA", "LLB", "LLM", "M.Arch", "M.Com", "M.Ed", "M.Ped", "M.Pharma", "M.Sc", "M.Tech", "MA", "MBA", "MBBS", "MCA", "MD", "MDS", "MS", "NTT", "PGDCA", "PGDM", "Ph.D."
];

export const TUTOR_EXPERIENCE_LIST = [
  "Less than 1 Year", "1 to 3 Years", "3 to 5 Years", "5 to 10 Years", "More than 10 Years"
];

export const TUTOR_FEE_LIST = [
  "₹200/hr (Entry Level)", "₹300/hr (Standard)", "₹400/hr (Recommended)", "₹500/hr (Experienced)", "₹600/hr (Expert)", "₹700/hr (Senior)", "₹800/hr (Premium)", "₹1000+/hr (Specialist)"
];

export const CITIES_LIST = [
  "Ahmedabad",
  "Ajmer",
  "Allahabad",
  "Amritsar",
  "Anand",
  "Armoor",
  "Aurangabad",
  "Bangalore",
  "Bareilly",
  "Belagavi",
  "Belgaum",
  "Bhilai",
  "Bhilwara",
  "Bhiwadi",
  "Bhopal",
  "Bhubaneswar",
  "Bilaspur",
  "Bokaro",
  "Burdwan",
  "Chandigarh",
  "Chennai",
  "Cochin",
  "Coimbatore",
  "Cuttack",
  "Dehradun",
  "Delhi",
  "Dhanbad",
  "Dharwad",
  "Faridabad",
  "Gandhinagar",
  "Gangtok",
  "Ghaziabad",
  "Goa",
  "Gorakhpur",
  "Greater Noida",
  "Gulbarga",
  "Guntur",
  "Gurgaon",
  "Guwahati",
  "Gwalior",
  "Howrah",
  "Hyderabad",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jalgaon",
  "Jammu",
  "Jamnagar",
  "Jodhpur",
  "Jorhat",
  "Kakinada",
  "Kalyan",
  "Kanpur",
  "Khanna",
  "Kolhapur",
  "Kolkata",
  "Kota",
  "Latur",
  "Leh",
  "Liluah",
  "Lucknow",
  "Ludhiana",
  "Machillipatnam",
  "Madurai",
  "Mangalore",
  "Manipal",
  "Meerut",
  "Mohali",
  "Moradabad",
  "Mumbai",
  "Mysuru",
  "Nadiad",
  "Nagpur",
  "Nanded",
  "Narsipatnam",
  "Nashik",
  "Nizamabad",
  "Noida",
  "Panchkula",
  "Panipat",
  "Pathankot",
  "Patiala",
  "Patna",
  "Pondicherry",
  "Pune",
  "Raipur",
  "Rajkot",
  "Ranchi",
  "Rourkela",
  "Salem",
  "Siliguri",
  "Sri Ganganagar",
  "Srinagar",
  "Surat",
  "Thane",
  "Thrissur",
  "Trivandrum",
  "Tumakuru",
  "Udaipur",
  "Ujjain",
  "Vadodara",
  "Vellore",
  "Vijayawada",
  "Vizag",
  "Vizianagaram",
  "Warangal",
  "Yamunanagar",
  "Zirakpur"
];

export const CLASSES_LIST = ["Class I to V", "Class VI to VIII", "Class IX to X", "Class XI to XII", "Entrance Exam & Specialization"];

export const SPECIALIZED_SUB_CATEGORIES: Record<string, string[]> = {
  "Entrance Exam & Specialization": ["JEE", "NEET", "IELTS / TOEFL", "Foreign Languages", "Regional & Indian Languages"]
};

export const SPECIALIZED_SUBJECTS: Record<string, any> = {
  "JEE": [
    "Physics (IIT-JEE Mains & Advanced)",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Mathematics (IIT-JEE Mains & Advanced)"
  ],
  "NEET": [
    "Physics (NEET Level)",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Botany",
    "Zoology"
  ],
  "IELTS / TOEFL": [
    "Speaking & Listening",
    "Reading & Writing",
    "General Training Prep",
    "Academic Test Prep"
  ],
  "Foreign Languages": {
    "Most Popular & Academic": [
      "English (Spoken, Business & Corporate)",
      "French (School Curriculum & DELF Prep)",
      "German (Goethe Institute Exam Prep)",
      "Spanish (DELE Exam Prep)"
    ],
    "Asian Languages - High Demand": [
      "Japanese (JLPT N5 to N1 Prep)",
      "Mandarin / Chinese (HSK Prep)",
      "Korean (TOPIK Exam Prep)",
      "Arabic (Modern Standard & Conversational)"
    ],
    "European Languages": [
      "Italian",
      "Russian",
      "Portuguese"
    ]
  },
  "Regional & Indian Languages": {
    "National & Classical": [
      "Hindi (Academic & Spoken)",
      "Sanskrit",
      "Urdu"
    ],
    "North & West India": [
      "Punjabi",
      "Gujarati",
      "Marathi",
      "Marwari / Rajasthani",
      "Kashmiri",
      "Konkani",
      "Sindhi"
    ],
    "South India": [
      "Tamil",
      "Telugu",
      "Kannada",
      "Malayalam"
    ],
    "East & Northeast India": [
      "Bengali",
      "Odia",
      "Assamese",
      "Maithili",
      "Nepali",
      "Manipuri"
    ]
  }
};

export const CLASS_GROUP_MAPPING: Record<string, string[]> = {
  "Class I to V": ["1st Std", "2nd Std", "3rd Std", "4th Std", "5th Std"],
  "Class VI to VIII": ["6th Std", "7th Std", "8th Std"],
  "Class IX to X": ["9th Std", "10th Std"],
  "Class XI to XII": ["11th Std", "12th Std"],
  "Competitive": ["NEET", "JEE", "CUET", "NDA", "CLAT", "Competitive", "Entrance"],
  "Language": ["French", "German", "Spanish", "IELTS", "TOEFL", "Language", "English Speaking"]
};

export const CLASS_SUBJECTS_DATA: Record<string, string[]> = {
  "Class I to V": ["All Subjects (General)", "English", "Hindi", "Maths", "EVS", "Jolly Phonics", "Abacus", "Vedic Maths", "Computer", "Cursive Writing", "Storytelling", "Art & Craft"],
  "Class VI to VIII": ["Maths", "Science", "Social Science (SST)", "English", "Hindi", "Sanskrit", "French", "German", "Spanish", "Computer/ICT", "Robotics"],
  "Class IX to X": ["Maths (Standard/Basic)", "Physics", "Chemistry", "Biology", "History", "Civics", "Geography", "Economics", "English (Language & Literature)", "Hindi (A/B)", "Sanskrit", "French", "German", "Information Technology (IT)", "Artificial Intelligence (AI)", "Robotics"],
  "Class XI to XII": ["Physics", "Chemistry", "Maths", "Biology", "Biotechnology", "IP", "Accounts", "Business Studies", "Economics", "Applied Maths", "Entrepreneurship", "Psychology", "Sociology", "Political Science", "History", "Geography", "Home Science", "Legal Studies", "English Core", "English Elective", "Physical Education", "Fine Arts"]
};

export const CITY_TO_LOCATIONS_DATA: Record<string, string[]> = {
  "Ahmedabad": [
    "Ahmedabad Cantonment",
    "Alam Roza",
    "Ambawadi",
    "Ambli",
    "Amraiwadi",
    "Asarwa",
    "Asarwa Chakla",
    "Aslali",
    "Ayojan Nagar",
    "Badarkha",
    "Bahiyal",
    "Bapunagar",
    "Bardolpura",
    "Behrampura",
    "Bhadaj",
    "Bhadra",
    "Bhairavnath Road",
    "Bodakdev",
    "Bopal",
    "CG Road",
    "CTM",
    "CTM Char Rasta",
    "Chaloda",
    "Chandkheda",
    "Chandlodiya",
    "Changodar",
    "Dabhoda",
    "Dani Limbada",
    "Dariapur",
    "Delhi Chakla",
    "Delhi Darwaja",
    "Detroj",
    "Dhandhuka",
    "Dholka",
    "Drive In Road",
    "Dudheshwar",
    "Dudheshwar Road",
    "Ellis Bridge",
    "Gandhi Road",
    "Geeta Mandir",
    "Geeta Mandir Road",
    "Ghatlodia",
    "Gheekanta",
    "Gheekanta Road",
    "Ghodasar",
    "Girdharnagar",
    "Gomtipur",
    "Gota",
    "Gulbai Tekra",
    "Gurukul",
    "Hansol",
    "Hatkeshwar",
    "Income Tax",
    "India Colony",
    "Indrapuri",
    "Isanpur",
    "Jagatpur",
    "Jamalpur",
    "Jasodanagar",
    "Jawahar Chowk",
    "Jholapur",
    "Jodhpur",
    "Juhapura",
    "Juna Wadaj",
    "Kalupur",
    "Kalyanpura",
    "Kankaria",
    "Kankaria Road",
    "Kathwada",
    "Khadia",
    "Khamasa",
    "Khanpur",
    "Kharna",
    "Khodiyarnagar",
    "Khokhra",
    "Krishnanagar",
    "Kubernagar",
    "Lambha",
    "Madhupura",
    "Makarba",
    "Manek Chowk",
    "Maninagar",
    "Meghani Nagar",
    "Memnagar",
    "Mirzapur",
    "Mirzapur Road",
    "Mithakali",
    "Motera",
    "Nandej",
    "Naranpura",
    "Naroda",
    "Naroda GIDC",
    "Naroda Road",
    "Narodamuthiya",
    "Narol",
    "Nava Vadaj",
    "Navarangpura",
    "Nikol",
    "Nirnay Nagar",
    "Noblenagar",
    "Odhav",
    "Odhav GIDC",
    "Odhav Road",
    "Paldi",
    "Pankore Naka",
    "Patharkuva",
    "Polarpur",
    "Prahlad Nagar",
    "Raipur",
    "Rajpur",
    "Rajpur Gomtipur",
    "Rakhial",
    "Ramol",
    "Ranip",
    "Ranna Park",
    "Ratan Pole",
    "Revdi Bazaar",
    "Sabarmati",
    "Saijpur",
    "Saijpur Bogha",
    "Sanand",
    "Sarangpur",
    "Saraspur",
    "Sardar Nagar",
    "Sarkhej",
    "Sarkhej Gandhinagar Highway",
    "Satellite",
    "Satellite Road",
    "Science City Road",
    "Shah Alam Road",
    "Shahibaug",
    "Shahibaug Road",
    "Shahpur",
    "Shardanagar",
    "Shastri Nagar",
    "Shela",
    "Shilaj",
    "Sindhu Bhavan Road",
    "Sola",
    "Sola Road",
    "Subhash Bridge",
    "Sukhrampura",
    "Tavdipura",
    "Teen Darwaja",
    "Thakkarbapa Nagar",
    "Thaltej",
    "Usmanpura",
    "Vasna",
    "Vastral",
    "Vastrapur",
    "Vatva",
    "Vatva GIDC",
    "Vejalpur",
    "Viramgam",
    "Walled City"
  ],
  "Ajmer": [
    "Adarsh Nagar",
    "Ana Sagar Link Road",
    "Beawar Road",
    "Civil Lines",
    "Dargah Area",
    "Ganj",
    "Madar Gate",
    "Panchsheel Nagar",
    "Pushkar Road",
    "Shastri Nagar",
    "Vaishali Nagar"
  ],
  "Amritsar": [
    "Basant Avenue",
    "Batala Road",
    "Chheharta",
    "Green Avenue",
    "Islamabad Area",
    "Lawrence Road",
    "Majitha Road",
    "Mall Road",
    "Putligarh",
    "Ram Tirath Road",
    "Ranjit Avenue",
    "Verka",
    "White Avenue"
  ],
  "Anand": [
    "Bakrol",
    "Chikhodra",
    "Gamdi",
    "Iscon Area",
    "Jitodia",
    "Karamsad",
    "Lambhvel",
    "Mogar",
    "Sardar Ganj",
    "Vallabh Vidyanagar"
  ],
  "Armoor": [
    "Ambedkar Chowk",
    "Bus Stand Area",
    "Bypass Road",
    "Gandhi Nagar",
    "Housing Board Colony",
    "Market Road",
    "Shanti Nagar",
    "Teachers Colony"
  ],
  "Aurangabad": [
    "Bajaj Nagar",
    "CIDCO",
    "Garkheda",
    "Harsul",
    "Jalna Road",
    "Kranti Chowk",
    "Mukundwadi",
    "Osmanpura",
    "Paithan Road",
    "Ulkanagari",
    "Waluj"
  ],
  "Bareilly": [
    "Alakhnath",
    "Civil Lines",
    "Dohra Road",
    "Faridpur Road",
    "Green Park Colony",
    "Izatnagar",
    "Karamchari Nagar",
    "Model Town",
    "Pilibhit Bypass Road",
    "Prem Nagar",
    "Rajendra Nagar",
    "Shyam Ganj",
    "Subhash Nagar"
  ],
  "Belagavi": [
    "Angol",
    "Ashok Nagar",
    "Camp Area",
    "Hanuman Nagar",
    "Hindwadi",
    "Mahantesh Nagar",
    "Shahapur",
    "Tilakwadi",
    "Vadgaon"
  ],
  "Belgaum": [
    "Bhagya Nagar",
    "College Road",
    "Fort Road",
    "Malmaruti Extension",
    "Nehru Nagar",
    "Ramteerth Nagar",
    "Rani Chennamma Nagar"
  ],
  "Bangalore": [
    "Adugodi",
    "Agara",
    "Agram",
    "Airport Road",
    "Amruthahalli",
    "Anand Nagar",
    "Anjanapura",
    "Arekere",
    "Attibele",
    "Austin Town",
    "BTM Layout",
    "Banaswadi",
    "Bannerghatta",
    "Bannerghatta Road",
    "Basavanagudi",
    "Basaveshwar Nagar",
    "Begur",
    "Bellandur",
    "Benson Town",
    "Bettahalasur",
    "Bidadi",
    "Bidare Agrahara",
    "Bidrahalli",
    "Billekahalli",
    "Bommanahalli",
    "Bommasandra",
    "Byatarayanapura",
    "C.V. Raman Nagar",
    "Chamarajpet",
    "Chandapura",
    "Channasandra",
    "Chikkalasandra",
    "Chikkamagaluru",
    "Cleveland Town",
    "Cooke Town",
    "Cox Town",
    "Cubbon Park",
    "Dasarahalli",
    "Devanahalli",
    "Devinagar",
    "Dharmaram",
    "Doddaballapur",
    "Doddakallasandra",
    "Domlur",
    "Dooravani Nagar",
    "Ejipura",
    "Electronic City",
    "Fraser Town",
    "Gandhi Nagar",
    "Ganganagar",
    "Gattigere",
    "Gollahalli",
    "Gottigere",
    "Govindaraja Nagar",
    "Gowdanapalya",
    "H.A.L. Old Airport Road",
    "HBR Layout",
    "HMT Layout",
    "HSR Layout",
    "Hennur",
    "Hennur Road",
    "Herohalli",
    "Hesaraghatta",
    "Hesaraghatta Main Road",
    "Hoodi",
    "Horamavu",
    "Hosakerehalli",
    "Hosur Road",
    "Hulimavu",
    "Indiranagar",
    "JP Nagar",
    "Jakkur",
    "Jalahalli",
    "Jayamahal",
    "Jayanagar",
    "Jnanabharathi",
    "Kadugodi",
    "Kadugodi Plantation",
    "Kaggadasapura",
    "Kaggalipura",
    "Kakolu",
    "Kalkere",
    "Kalyan Nagar",
    "Kamakshipalya",
    "Kammanahalli",
    "Kanakapura Road",
    "Kanchenahalli",
    "Kannamangala",
    "Kasturi Nagar",
    "Kathriguppe",
    "Kempegowda International Airport",
    "Kengeri",
    "Kengeri Satellite Town",
    "Kodichikkanahalli",
    "Kogilu",
    "Konanakunte",
    "Kothanur",
    "Kothnur Dinne",
    "Krishnarajapuram",
    "Kumaraswamy Layout",
    "Kumbalgodu",
    "Kundalahalli",
    "Langford Town",
    "Lavelle Road",
    "Lottegollahalli",
    "MCECHS Layout",
    "Madiwala",
    "Magadi Road",
    "Mahadevapura",
    "Majestic",
    "Marathahalli",
    "Maruthi Sevanagar",
    "Mathikere",
    "Medahalli",
    "Mysore Road",
    "NRI Layout",
    "Nagadevanahalli",
    "Nagarbhavi",
    "Nagasandra",
    "Nandi Hills",
    "Nandini Layout",
    "New Thippasandra",
    "Old Airport Road",
    "Old Madras Road",
    "Padmanabhanagar",
    "Palace Road",
    "Panduranga Nagar",
    "Peenya",
    "Puttenahalli",
    "R.T. Nagar",
    "R.V. College of Engineering",
    "RMV Extension",
    "Race Course Road",
    "Rachenahalli",
    "Rajajinagar",
    "Rajanukunte",
    "Ramamurthy Nagar",
    "Ramasandra",
    "Richmond Road",
    "Richmond Town",
    "Sadashivanagar",
    "Sahakar Nagar",
    "Sampangiram Nagar",
    "Sanjay Nagar",
    "Sarjapur",
    "Sarjapur Road",
    "Seshadripuram",
    "Shankarapura",
    "Shivajinagar",
    "Silk Board",
    "Singapura",
    "Singasandra",
    "Soladevanahalli",
    "Srinagara",
    "St. Marks Road",
    "Subramanyapura",
    "Sulikere",
    "Sultanpalya",
    "Tavarekere",
    "Thigalarapalya",
    "Thindlu",
    "Thippasandra",
    "Tumkur Road",
    "Ulsoor",
    "Uttarahalli",
    "Varthur",
    "Vasanth Nagar",
    "Vidyaranyapura",
    "Vijayanagar",
    "Vimanapura",
    "Virgonagar",
    "Viswaneedam",
    "Viveka Nagar",
    "Whitefield",
    "Williams Town",
    "Wilson Garden",
    "Yelahanka",
    "Yelahanka New Town",
    "Yeshwanthpur"
  ],
  "Bhilai": [
    "Bhilai Nagar",
    "Civic Centre",
    "Durg Road",
    "Nehru Nagar",
    "Power House",
    "Risali",
    "Ruabandha",
    "Smriti Nagar",
    "Supela"
  ],
  "Bhilwara": [
    "Azad Nagar",
    "Bapunagar",
    "Gandhi Nagar",
    "Indira Colony",
    "Kareda Chouraha",
    "Sangam Nagar",
    "Shastri Nagar",
    "Subhash Nagar"
  ],
  "Bhiwadi": [
    "Alwar Bypass Road",
    "Capital Mall Area",
    "Chopanki",
    "Phase 1",
    "Phase 2",
    "Phase 3",
    "Tapukara Road",
    "UIT Sector 2",
    "UIT Sector 3"
  ],
  "Bhopal": [
    "10 No Market",
    "Airport Road",
    "Anand Nagar",
    "Anand Nagar Extension",
    "Arera Colony",
    "Ashoka Garden",
    "Awadhpuri",
    "Ayodhya Bypass",
    "BHEL Township",
    "Bagh Mughalia",
    "Bairagarh",
    "Bairagarh Cantt",
    "Bairagarh Chichali",
    "Bairagarh Kalan",
    "Barkheda",
    "Basant Kunj",
    "Bawadia Kalan",
    "Berasia",
    "Berasiya Road",
    "Bhopal Talkies Area",
    "Bittan Market",
    "Chanchal Chowk",
    "Char Imli",
    "Chhola Road",
    "Chuna Bhatti",
    "Gandhi Nagar",
    "Govindpura",
    "Gufa Mandir",
    "Gulmohar Colony",
    "Habibganj",
    "Hamidia Road",
    "Hoshangabad Road",
    "Idgah Hills",
    "Indrapuri",
    "JP Nagar",
    "Jail Road",
    "Jawahar Chowk",
    "Kamla Park",
    "Karishma Hills",
    "Karond",
    "Kasturba Nagar",
    "Katara Hills",
    "Kohefiza",
    "Kolar Road",
    "Lalghati",
    "MP Nagar",
    "Mandideep",
    "Misrod",
    "Narela Shankari",
    "Nehru Nagar",
    "New Market",
    "Nizamuddin Colony",
    "North TT Nagar",
    "Patel Nagar",
    "Peer Gate",
    "Piplani",
    "Ratibad",
    "Roshanpura",
    "Saket Nagar",
    "Shahpura",
    "Shyamla Hills",
    "South TT Nagar",
    "Station Road",
    "Subhash Nagar",
    "T. T. Nagar",
    "Talaiya"
  ],
  "Bhubaneswar": [
    "Baramunda",
    "Chandrasekharpur",
    "Dumduma",
    "Jayadev Vihar",
    "Kalinga Nagar",
    "Kharavel Nagar",
    "Mancheswar",
    "Nayapalli",
    "Old Town",
    "Patia",
    "Rasulgarh",
    "Saheed Nagar"
  ],
  "Bilaspur": [
    "Gandhi Chowk",
    "Mangla",
    "Nehru Nagar",
    "Sarkanda",
    "Tifra",
    "Tikrapara",
    "Torwa",
    "Vyapar Vihar"
  ],
  "Bokaro": [
    "Balidih",
    "Chas",
    "City Centre",
    "Co-operative Colony",
    "Sector 12",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Sector 9"
  ],
  "Burdwan": [
    "Alamganj",
    "Baburbag",
    "Court Area",
    "Golapbag",
    "Khosbagan",
    "Nutanpally",
    "Sripally",
    "Vivekananda College Area"
  ],
  "Chandigarh": [
    "Khuda Alisher",
    "Mani Majra",
    "Mauli Jagran",
    "Sector 1",
    "Sector 10",
    "Sector 11",
    "Sector 15",
    "Sector 17",
    "Sector 2",
    "Sector 22",
    "Sector 23",
    "Sector 26",
    "Sector 27",
    "Sector 3",
    "Sector 30",
    "Sector 31",
    "Sector 34",
    "Sector 35",
    "Sector 39",
    "Sector 4",
    "Sector 41",
    "Sector 45",
    "Sector 47",
    "Sector 49",
    "Sector 5",
    "Sector 50",
    "Sector 52",
    "Sector 53",
    "Sector 55",
    "Sector 56",
    "Sector 61",
    "Sector 62",
    "Sector 63",
    "Sector 64",
    "Sector 66",
    "Sector 67",
    "Sector 7",
    "Sector 71",
    "Sector 76",
    "Sector 77",
    "Sector 79",
    "Sector 8",
    "Sector 80",
    "Sector 82",
    "Sector 85",
    "Sector 86",
    "Sector 9",
    "Sector 90",
    "Sector 91",
    "Sector 92"
  ],
  "Chennai": [
    "Adambakkam",
    "Adyar",
    "Alandur",
    "Alapakkam",
    "Alwarpet",
    "Ambattur",
    "Aminjikarai",
    "Anna Nagar",
    "Anna Salai",
    "Annanur",
    "Arumbakkam",
    "Ashok Nagar",
    "Avadi",
    "Ayanavaram",
    "Besant Nagar",
    "Broadway",
    "Chintadripet",
    "Chitlapakkam",
    "Choolai",
    "Choolaimedu",
    "Chromepet",
    "Egmore",
    "Ekkattuthangal",
    "Ennore",
    "Foreshore Estate",
    "George Town",
    "Gopalapuram",
    "Guindy",
    "Injambakkam",
    "Iyappanthangal",
    "Iyyapanthangal",
    "Jafferkhanpet",
    "Jalladianpet",
    "K.K. Nagar",
    "Kadappakkam",
    "Kallikuppam",
    "Kanathur",
    "Kandanchavadi",
    "Kandigai",
    "Kangeyam",
    "Kattupakkam",
    "Kazhipattur",
    "Keelkattalai",
    "Kilpauk",
    "Kodambakkam",
    "Kodungaiyur",
    "Kolathur",
    "Kompakkam",
    "Kottivakkam",
    "Kotturpuram",
    "Kovalam",
    "Kovilambakkam",
    "Kovur",
    "Koyambedu",
    "Kundrathur",
    "Madambakkam",
    "Madhavaram",
    "Madhavaram Milk Colony",
    "Madipakkam",
    "Maduravoyal",
    "Manali",
    "Manapakkam",
    "Mangadu",
    "Mannady",
    "Maraimalai Nagar",
    "Medavakkam",
    "Meenambakkam",
    "Mogappair",
    "Moolakadai",
    "Mount Road",
    "Mugalivakkam",
    "Mylapore",
    "Nanganallur",
    "Nanmangalam",
    "Nerkundram",
    "Nesapakkam",
    "Nolambur",
    "Nungambakkam",
    "Old Mahabalipuram Road (OMR)",
    "Otteri",
    "Padur",
    "Palavakkam",
    "Pallavaram",
    "Pallikaranai",
    "Pammal",
    "Perambur",
    "Perumbakkam",
    "Perungalathur",
    "Perungudi",
    "Poonamallee",
    "Porur",
    "Purasaiwakkam",
    "Puthagaram",
    "Puzhal",
    "Puzhuthivakkam",
    "Red Hills",
    "Royapettah",
    "Royapuram",
    "Saidapet",
    "Saligramam",
    "Santhome",
    "Selaiyur",
    "Semmancheri",
    "Shenoy Nagar",
    "Sholinganallur",
    "Sithalapakkam",
    "Sowcarpet",
    "SriramNagar",
    "St. Thomas Mount",
    "T Nagar",
    "Tambaram",
    "Taramani",
    "Teynampet",
    "Thirumazhisai",
    "Thirumullaivoyal",
    "Thiruneermalai",
    "Thiruninravur",
    "Thiruvanmiyur",
    "Thiruverkadu",
    "Thoraipakkam",
    "Tindivanam",
    "Tondiarpet",
    "Ullagaram",
    "Urapakkam",
    "Vadapalani",
    "Valasaravakkam",
    "Vanagaram",
    "Vandalur",
    "Velachery",
    "Velappanchavadi",
    "Vengaivasal",
    "Villivakkam",
    "Virugambakkam",
    "Vyasarpadi",
    "Washermanpet",
    "West Mambalam"
  ],
  "Coimbatore": [
    "Avinashi Road",
    "Ganapathy",
    "Gandhipuram",
    "Kalapatti",
    "Kovaipudur",
    "Kuniamuthur",
    "Peelamedu",
    "RS Puram",
    "Saibaba Colony",
    "Saravanampatti",
    "Singanallur",
    "Sulur",
    "Thudiyalur",
    "Town Hall",
    "Ukkadam",
    "Vadavalli"
  ],
  "Cuttack": [
    "Badambadi",
    "Buxi Bazaar",
    "CDA Sector 10",
    "CDA Sector 6",
    "CDA Sector 7",
    "Choudwar Road",
    "College Square",
    "Jobra",
    "Link Road",
    "Mangalabag",
    "Tulasipur"
  ],
  "Dehradun": [
    "Ballupur",
    "Clement Town",
    "Dalanwala",
    "ISBT Area",
    "Jakhan",
    "Karbari Grant",
    "Mussoorie Road",
    "Nehru Colony",
    "Patel Nagar",
    "Prem Nagar",
    "Race Course",
    "Rajpur Road",
    "Sahastradhara Road",
    "Selakui",
    "Vasant Vihar"
  ],
  "Delhi": [
    "Anand Niketan",
    "Anand Parbat",
    "Ashok Vihar",
    "Burari",
    "Chattarpur",
    "Civil Lines",
    "Connaught Place",
    "Defence Colony",
    "Dwarka",
    "Dwarka Mor",
    "Greater Kailash",
    "Green Park",
    "Hauz Khas",
    "IP Extension",
    "Janakpuri",
    "Jangpura",
    "Jor Bagh",
    "Kalkaji",
    "Karampura",
    "Lajpat Nagar",
    "Malviya Nagar",
    "Mayur Vihar",
    "Mukherjee Nagar",
    "Narela",
    "Panchsheel Park",
    "Paschim Puri",
    "Paschim Vihar",
    "Pitampura",
    "Preet Vihar",
    "Rajouri Garden",
    "Rohini",
    "Safdarjung Enclave",
    "Sainik Farms",
    "Saket",
    "Shahpur Jat",
    "Shalimar Bagh",
    "Uttam Nagar",
    "Vasant Kunj",
    "Vasant Vihar",
    "Vikaspuri",
    "Yamuna Vihar"
  ],
  "Dhanbad": [
    "Baliapur",
    "Bank More",
    "Barwadda",
    "Govindpur",
    "Hirapur",
    "Housing Colony",
    "Jharia",
    "Katras",
    "Kusunda",
    "Saraidhela"
  ],
  "Dharwad": [
    "Gopankoppa",
    "Hosayellapur",
    "Jubilee Circle",
    "Kalyan Nagar",
    "Lakamanahalli",
    "Malmaddi",
    "Navanagar",
    "Saptapur",
    "Vidyanagar"
  ],
  "Faridabad": [
    "NIT",
    "Sector 1",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 13",
    "Sector 14",
    "Sector 15",
    "Sector 16",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 2",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 29",
    "Sector 3",
    "Sector 30",
    "Sector 31",
    "Sector 32",
    "Sector 33",
    "Sector 34",
    "Sector 35",
    "Sector 36",
    "Sector 37",
    "Sector 38",
    "Sector 39",
    "Sector 4",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 44",
    "Sector 45",
    "Sector 46",
    "Sector 47",
    "Sector 48",
    "Sector 49",
    "Sector 5",
    "Sector 50",
    "Sector 51",
    "Sector 52",
    "Sector 53",
    "Sector 54",
    "Sector 55",
    "Sector 56",
    "Sector 57",
    "Sector 58",
    "Sector 59",
    "Sector 6",
    "Sector 60",
    "Sector 61",
    "Sector 62",
    "Sector 63",
    "Sector 64",
    "Sector 65",
    "Sector 66",
    "Sector 67",
    "Sector 68",
    "Sector 69",
    "Sector 7",
    "Sector 70",
    "Sector 71",
    "Sector 72",
    "Sector 73",
    "Sector 74",
    "Sector 75",
    "Sector 76",
    "Sector 77",
    "Sector 78",
    "Sector 79",
    "Sector 8",
    "Sector 80",
    "Sector 81",
    "Sector 81A",
    "Sector 82",
    "Sector 83",
    "Sector 84",
    "Sector 85",
    "Sector 86",
    "Sector 87",
    "Sector 88",
    "Sector 89",
    "Sector 9",
    "Sector 90",
    "Sector 91"
  ],
  "Gandhinagar": [
    "Sector 1",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 13",
    "Sector 14",
    "Sector 15",
    "Sector 16",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 2",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 29",
    "Sector 3",
    "Sector 30",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Sector 7",
    "Sector 8",
    "Sector 9"
  ],
  "Gangtok": [
    "Arithang",
    "Burtuk",
    "Deorali",
    "Development Area",
    "Lower Sichey",
    "Ranipool",
    "Tadong",
    "Tibet Road",
    "Upper Sichey"
  ],
  "Ghaziabad": [
    "Ashok Nagar",
    "Crossing Republik",
    "Gandhi Nagar",
    "Ghantaghar",
    "Govindpuram",
    "Indirapuram",
    "Kaushambi",
    "Kavi Nagar",
    "Loni",
    "Mohan Nagar",
    "Nehru Nagar",
    "Patel Nagar",
    "Pratap Vihar",
    "Raj Nagar",
    "Raj Nagar Extension",
    "Rajendra Nagar",
    "Sanjay Nagar",
    "Shalimar Garden",
    "Shastri Nagar",
    "Siddharth Vihar",
    "Surya Nagar",
    "Vaishali",
    "Vasundhara",
    "Vijay Nagar",
    "Wave City NH24"
  ],
  "Goa": [
    "Anjuna",
    "Baga",
    "Calangute",
    "Candolim",
    "Dona Paula",
    "Mapusa",
    "Margao",
    "Panjim",
    "Ponda",
    "Porvorim",
    "Vasco da Gama"
  ],
  "Gorakhpur": [
    "Basharatpur",
    "Chargawan",
    "Civil Lines",
    "Golghar",
    "Medical College Road",
    "Rapti Nagar",
    "Rustampur",
    "Shahpur",
    "Taramandal"
  ],
  "Greater Noida": [
    "Alpha 1",
    "Alpha 2",
    "Beta 1",
    "Beta 2",
    "Chi 1",
    "Chi 2",
    "Chi 3",
    "Chi 4",
    "Chi 5",
    "Delta 1",
    "Delta 2",
    "Delta 3",
    "Delta 4",
    "Eco Village 1",
    "Eco Village 2",
    "Eco Village 3",
    "Eco Village 4",
    "Gamma 1",
    "Gamma 2",
    "Knowledge Park 1",
    "Knowledge Park 2",
    "Knowledge Park 3",
    "Knowledge Park 4",
    "MU",
    "Noida Extension",
    "Omega",
    "Omicron 1",
    "Omicron 2",
    "Omicron 3",
    "PI 1",
    "PI 2",
    "PI 3",
    "Pari Chowk",
    "Sigma 1",
    "Sigma 2",
    "Sigma 3",
    "Sigma 4",
    "Swarn Nagari",
    "Techzone 1",
    "Techzone 2",
    "Techzone 4",
    "Techzone 5",
    "Xu 1",
    "Xu 2",
    "Yamuna Expressway",
    "Zeta 1",
    "Zeta 2"
  ],
  "Gulbarga": [
    "Jewargi Road",
    "Old City",
    "Sedam Road",
    "Shah Bazar",
    "Station Road",
    "Super Market Area",
    "Veeresh Nagar",
    "Vidyanagar"
  ],
  "Guntur": [
    "Arundelpet",
    "Brindavan Gardens",
    "Brodipet",
    "Chandramouli Nagar",
    "Koritepadu",
    "Lakshmipuram",
    "Pattabhipuram",
    "Syamalanagar"
  ],
  "Gurgaon": [
    "DLF Phase 1",
    "DLF Phase 2",
    "DLF Phase 3",
    "DLF Phase 4",
    "DLF Phase 5",
    "IMT Manesar",
    "Maruti Kunj",
    "Palam Vihar",
    "Sector 1",
    "Sector 10",
    "Sector 102",
    "Sector 103",
    "Sector 104",
    "Sector 105",
    "Sector 107",
    "Sector 108",
    "Sector 109",
    "Sector 10A",
    "Sector 11",
    "Sector 110",
    "Sector 111",
    "Sector 112",
    "Sector 113",
    "Sector 12",
    "Sector 12A",
    "Sector 13",
    "Sector 14",
    "Sector 15",
    "Sector 17",
    "Sector 18",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 23A",
    "Sector 24",
    "Sector 25",
    "Sector 27",
    "Sector 28",
    "Sector 3",
    "Sector 30",
    "Sector 31",
    "Sector 33",
    "Sector 36",
    "Sector 37",
    "Sector 37C",
    "Sector 37D",
    "Sector 38",
    "Sector 39",
    "Sector 4",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 45",
    "Sector 46",
    "Sector 47",
    "Sector 48",
    "Sector 49",
    "Sector 5",
    "Sector 50",
    "Sector 51",
    "Sector 52",
    "Sector 53",
    "Sector 54",
    "Sector 55",
    "Sector 56",
    "Sector 57",
    "Sector 58",
    "Sector 59",
    "Sector 6",
    "Sector 60",
    "Sector 61",
    "Sector 62",
    "Sector 63",
    "Sector 65",
    "Sector 66",
    "Sector 67",
    "Sector 68",
    "Sector 69",
    "Sector 7",
    "Sector 70",
    "Sector 70A",
    "Sector 71",
    "Sector 72",
    "Sector 73",
    "Sector 76",
    "Sector 77",
    "Sector 79",
    "Sector 8",
    "Sector 81",
    "Sector 82",
    "Sector 82A",
    "Sector 83",
    "Sector 84",
    "Sector 85",
    "Sector 86",
    "Sector 88",
    "Sector 89",
    "Sector 9",
    "Sector 90",
    "Sector 91",
    "Sector 92",
    "Sector 93",
    "Sector 95",
    "Sector 9A",
    "Sushant Lok 1",
    "Sushant Lok 2",
    "Sushant Lok 3"
  ],
  "Guwahati": [
    "Adabari",
    "Azara",
    "Basistha",
    "Beharbari",
    "Beltola",
    "Bhangagarh",
    "Bhetapara",
    "Boragaon",
    "Borjhar",
    "Chandmari",
    "Christian Basti",
    "Dispur",
    "GS Road",
    "Ganeshguri",
    "Garchuk",
    "Geetanagar",
    "Hatigaon",
    "Jalukbari",
    "Jyotikuchi",
    "Kahilipara",
    "Khanapara",
    "Kharghuli",
    "Lal Ganesh",
    "Lokhra",
    "Maligaon",
    "Narengi",
    "Noonmati",
    "Panjabari",
    "Patharquerry",
    "RG Baruah Road",
    "Rehabari",
    "Silpukhuri",
    "Six Mile",
    "Ulubari",
    "Uzan Bazar",
    "Zoo Road"
  ],
  "Gwalior": [
    "Alkapuri",
    "City Centre",
    "Dabra Road",
    "Govindpuri",
    "Hazira",
    "Lashkar",
    "Maharajpura",
    "Morar",
    "Patel Nagar",
    "Phool Bagh",
    "Thatipur"
  ],
  "Howrah": [
    "Avani Riverside Area",
    "Bally",
    "Belur",
    "Kadamtala",
    "Liluah",
    "Pilkhana",
    "Salkia",
    "Santragachi",
    "Shibpur"
  ],
  "Hyderabad": [
    "A. S. Rao Nagar",
    "Abids",
    "Adibatla",
    "Aghapura",
    "Almasguda",
    "Alwal",
    "Amberpet",
    "Ameerpet",
    "Asif Nagar",
    "Attapur",
    "Bachupally",
    "Badangpet",
    "Bahadurpura",
    "Bandlaguda Jagir",
    "Banjara Hills",
    "Basheerbagh",
    "Beeramguda",
    "Boduppal",
    "Bowenpally",
    "Buddha Nagar",
    "Chandanagar",
    "Chandrayangutta",
    "Dandamudi Enclave",
    "Dilsukhnagar",
    "Gachibowli",
    "Gajularamaram",
    "Gopanpally",
    "Habsiguda",
    "Hafeezpet",
    "Hayathnagar",
    "Himayatnagar",
    "Jeedimetla",
    "Jubilee Hills",
    "Kachiguda",
    "Kanchan Bagh",
    "Karmanghat",
    "Karwan",
    "Khajaguda",
    "Kompally",
    "Kondapur",
    "Kothapet",
    "Kowkoor",
    "Kukatpally",
    "Kushaiguda",
    "LB Nagar",
    "Lingampally",
    "Madeenaguda",
    "Madhapur",
    "Malakpet",
    "Manikonda",
    "Mansoorabad",
    "Medchal",
    "Miyapur",
    "Moti Nagar",
    "Nacharam",
    "Nagole",
    "Nallagandla",
    "Nampally",
    "Narsingi",
    "Neredmet",
    "Nizampet",
    "Osmannagar",
    "Padmarao Nagar",
    "Patancheru",
    "Peerzadiguda",
    "Pragathi Nagar",
    "Quthbullapur",
    "RTC X Roads",
    "Raidurg",
    "Rajendra Nagar",
    "Rangareddy",
    "Safilguda",
    "Saidabad",
    "Sanath Nagar",
    "Secunderabad",
    "Secunderabad Cantonment",
    "Serilingampally",
    "Shaikpet",
    "Shamshabad",
    "Sitaphalmandi",
    "Somajiguda",
    "Suraram",
    "Tellapur",
    "Toli Chowki",
    "Uppal",
    "Upparapalli",
    "Vanasthalipuram",
    "Warasiguda",
    "West Marredpally",
    "Yousufguda"
  ],
  "Indore": [
    "AB Road",
    "Ambedkar Nagar",
    "Azad Nagar",
    "Bada Bangarda",
    "Bhanwarkuan",
    "Bicholi Mardana",
    "Bijalpur",
    "Chandan Nagar",
    "Chandra Nagar",
    "Dewas Naka",
    "Geeta Bhawan",
    "Gulmohar Colony",
    "IDA Scheme No 134",
    "Jhalariya",
    "Kanadia Main Road",
    "Khajrana",
    "Khandwa Road",
    "LIG Colony",
    "MR 10 Road",
    "Mahalaxmi Nagar",
    "Malviya Nagar",
    "Malwa County",
    "Manglia",
    "Navlakha",
    "New Rani Bagh",
    "Nipania",
    "Niranjanpur",
    "Palasia",
    "Pipliyahana",
    "Rajendra Nagar",
    "Rau",
    "Rau Colony",
    "Saket Nagar",
    "Sangam Nagar",
    "Satya Sai Chouraha",
    "Scheme No 114",
    "Scheme No 54",
    "Scheme No 78",
    "Silicon City",
    "Simrol",
    "South Tukoganj",
    "Sukhliya",
    "Super Corridor",
    "Talawali Chanda",
    "Ujjain Road",
    "Vaishali Nagar",
    "Vijay Nagar"
  ],
  "Jabalpur": [
    "Adhartal",
    "Cherital",
    "Garha",
    "Gwarighat",
    "Madan Mahal",
    "Napier Town",
    "Ranjhi",
    "Tilwara",
    "Vijay Nagar",
    "Wright Town"
  ],
  "Jaipur": [
    "Adarsh Nagar",
    "Ajmer Road",
    "Ambabari",
    "Amer",
    "Anandpuri",
    "Bagru",
    "Bajaj Nagar",
    "Bani Park",
    "Bapu Nagar",
    "Barkat Nagar",
    "Bassi",
    "C-Scheme",
    "Chaksu",
    "Chitrakoot",
    "Chomu",
    "Civil Lines",
    "Dudu",
    "Durgapura",
    "Gangapole",
    "Gokulpura",
    "Gopalpura Bypass",
    "Hanuman Nagar",
    "Harmada",
    "Hasanpura",
    "JLN Marg",
    "Jagatpura",
    "Jaisinghpura",
    "Jhotwara",
    "Kalwar Road",
    "Kanota",
    "Keshopura",
    "Kotputli",
    "Kukas",
    "Lal Bahadur Nagar",
    "Mahal Road",
    "Mahaveer Nagar",
    "Malviya Nagar",
    "Mansarovar",
    "Mansarovar Extension",
    "Model Town",
    "Murlipura",
    "Nehru Nagar",
    "Nirman Nagar",
    "Paldi Meena",
    "Patrakar Colony",
    "Phulera",
    "Pratap Nagar",
    "Raja Park",
    "Rambagh",
    "Rukanpura",
    "Sanganer",
    "Saraswati Nagar",
    "Shastri Nagar",
    "Shivaji Nagar",
    "Shyam Nagar",
    "Sikar Road",
    "Sirsi Road",
    "Sodala",
    "Sunder Nagar",
    "Tilak Nagar",
    "Tonk Road",
    "Vaishali Nagar",
    "Vidhyadhar Nagar",
    "Vishwakarma Industrial Area"
  ],
  "Jalandhar": [
    "Basti Bawa Khel",
    "Basti Sheikh",
    "Cantt Road",
    "Civil Lines",
    "Mithapur",
    "Model Town",
    "Nakodar Road",
    "Rama Mandi",
    "Urban Estate Phase 1",
    "Urban Estate Phase 2"
  ],
  "Jalgaon": [
    "Baliram Peth",
    "Deopur",
    "Khandesh Nagar",
    "MIDC Area",
    "Mehrun",
    "Pimprala",
    "Ring Road",
    "Shivaji Nagar",
    "Zilha Peth"
  ],
  "Jammu": [
    "Bakshi Nagar",
    "Bari Brahmana",
    "Bohri",
    "Channi Himmat",
    "Gandhi Nagar",
    "Janipur",
    "Shastri Nagar",
    "Talab Tillo",
    "Trikuta Nagar"
  ],
  "Jamnagar": [
    "Digvijay Plot",
    "GIDC Phase 1",
    "Gulab Nagar",
    "Indira Marg",
    "Jogvad",
    "Patel Colony",
    "Ranjit Sagar Road",
    "Saru Section Road"
  ],
  "Jodhpur": [
    "Basni",
    "Chopasni Road",
    "Mandore",
    "Pal Road",
    "Paota",
    "Pratap Nagar",
    "Ratanada",
    "Sardarpura",
    "Shastri Nagar"
  ],
  "Jorhat": [
    "A.T. Road Area",
    "Chandan Nagar",
    "Cinnamara",
    "Garali",
    "Kenduguri",
    "Pulibor",
    "Rowriah",
    "Tarajan"
  ],
  "Kakinada": [
    "Ashok Nagar",
    "Bhanugudi",
    "Gajuwaka Road Area",
    "Indrapalem",
    "Jagannaickpur",
    "Ramanayyapeta",
    "Sarpavaram"
  ],
  "Kalyan": [
    "Ambivli",
    "Gandhare",
    "Kalyan East",
    "Kalyan West",
    "Khadakpada",
    "Shahad",
    "Titwala Road Area",
    "Vithalwadi"
  ],
  "Kanpur": [
    "Ansari Marg",
    "Ansari Road",
    "Arya Nagar",
    "Barra",
    "Bethou",
    "Bharath Nagar",
    "Birhana Road",
    "Bypass Road",
    "Chunniganj",
    "Civil Lines",
    "Civil Lines Extension",
    "Dada Nagar",
    "Faizabad Road Colony",
    "Faizullahgz",
    "Gandhi Puram",
    "Govind Nagar",
    "Guava Khand",
    "Hindon X Road",
    "Jajmau",
    "Kakadeo",
    "Kalyanpur",
    "Kavila Nagar",
    "Kidwai Nagar",
    "Lal Bangla",
    "Lala Lajpat Rai Marg",
    "Meston Road",
    "Mitra College Road",
    "Mitraon",
    "Nandi Bazaar",
    "Naveen Market",
    "Nehru Nagar",
    "Nirala Nagar",
    "Niwari Nala",
    "Padampur",
    "Quest Khand",
    "Railway Hospital Colony",
    "Ratan Lal Nagar",
    "Rawatpur",
    "Rawatpur Railway Colony",
    "Rivalganj",
    "Saket Nagar",
    "Sarsaiya",
    "Sharda Nagar",
    "Shastri Nagar",
    "Shehzada Ganj",
    "Sihani Gate",
    "Swarn Jayanti Nagar",
    "Swaroop Nagar",
    "Tagore Marg",
    "Teliyarganj",
    "Tilak Nagar",
    "Vishnupuri"
  ],
  "Khanna": [
    "Civil Lines",
    "GT Road Area",
    "Green Avenue",
    "Model Town",
    "New Grain Market",
    "Samrala Road",
    "Ward No 9"
  ],
  "Cochin": [
    "Aluva",
    "Cheranallur",
    "Edappally",
    "Fort Kochi",
    "Kadavanthra",
    "Kakkanad",
    "Kalamassery",
    "Kaloor",
    "Marine Drive",
    "Mattancherry",
    "Palarivattom",
    "Panampilly Nagar",
    "Thevara",
    "Thrippunithura",
    "Tripunithura",
    "Vyttila"
  ],
  "Kolkata": [
    "Agarpara",
    "Alipore",
    "Amherst Street",
    "Andul",
    "Baghajatin",
    "Baguiati",
    "Ballygunge",
    "Bansdroni",
    "Baranagar",
    "Barrackpore",
    "Behala",
    "Belghoria",
    "Beliaghata",
    "Bidhannagar",
    "Cossipore",
    "Dum Dum",
    "EM Bypass",
    "Ganguli Bagan",
    "Garia",
    "Howrah",
    "Jadavpur",
    "Kankinara",
    "Kasba",
    "Lake Gardens",
    "Lake Town",
    "Maheshtala",
    "Manicktala",
    "Mukundapur",
    "Nagerbazar",
    "Naktala",
    "Narendrapur",
    "Narkel Bagan",
    "Nathpara",
    "New Town",
    "Picnic Garden",
    "Rajarhat",
    "Rajarhat Gopalpur",
    "Regent Park",
    "Salt Lake",
    "Sealdah",
    "Sodepur",
    "Sonarpur",
    "Taltala",
    "Thakurpukur",
    "Tollygunge",
    "Topsia",
    "Ultadanga"
  ],
  "Kolhapur": [
    "Jaysingpur Road",
    "Kadamwadi",
    "Kalamba",
    "Laxmipuri",
    "Rajarampuri",
    "Rankala",
    "Shahupuri",
    "Shiroli MIDC",
    "Tarabai Park",
    "Ujalaiwadi"
  ],
  "Kota": [
    "Dadabari",
    "Gumanpura",
    "Indira Vihar",
    "Jawahar Nagar",
    "Kunhadi",
    "Mahaveer Nagar",
    "Nayapura",
    "Rangbari",
    "Talwandi",
    "Vigyan Nagar"
  ],
  "Latur": [
    "Ausa Road",
    "Barshi Road",
    "Dayanand Gate",
    "Old MIDC",
    "Ram Nagar",
    "Renapur Naka",
    "Signal Camp",
    "Udgir Road"
  ],
  "Leh": [
    "Changspa",
    "Choglamsar",
    "Main Market",
    "Phyang",
    "Saboo",
    "Shey",
    "Skara",
    "Spituk",
    "Thiksey"
  ],
  "Liluah": [
    "Belur Math Road",
    "Don Bosco Area",
    "G.T. Road",
    "Liluah Station Area",
    "Salkia Extension"
  ],
  "Lucknow": [
    "Abidnagar",
    "Aerocity",
    "Aishbagh",
    "Alambagh",
    "Aliganj",
    "Anand Nagar",
    "Ashfaq Colony",
    "Ashiyana Colony",
    "Bakshi Ka Talab",
    "Bank Road",
    "Barabanki Road",
    "Baradari",
    "Bharat Nagar",
    "Bhootnath Market",
    "Charbagh",
    "Chinhat",
    "Dubagga",
    "Golbagh",
    "Gomti Nagar",
    "Gomti Nagar Extension",
    "Hazaratganj",
    "Indira Nagar",
    "Infront",
    "Jangali Nagri",
    "Jankipuram",
    "Juggi-Budhi",
    "Kaiserbagh",
    "Kalyanpur",
    "Kapoorthala",
    "Kashiya Nagar",
    "Khurram Nagar",
    "Kolkata Road",
    "Krishna Nagar",
    "Lucknow Cantt.",
    "Mahanagar",
    "Malakpet",
    "Malviya Nagar",
    "Nirala Nagar",
    "Pandey Nagar",
    "Pandu Nagar",
    "Rajajipuram",
    "Rajendra Nagar",
    "Rajiv Gandhi Puram",
    "Rani Laxmi Bai Marg",
    "Ravindrapalli",
    "Rudra Mahal",
    "Saadatganj",
    "Saket Nagar",
    "Samta Nagar",
    "Shaheed Path",
    "Sheetal Nagar",
    "Shram Nagar",
    "Sitapur Road",
    "Sushant Golf City",
    "Swaroop Nagar",
    "Tagore Marg",
    "Takrohi Bazaar",
    "Talkatora",
    "Ujariyaon",
    "Vishwas Khand",
    "Volga Bazaar",
    "Vrindavan Yojna"
  ],
  "Ludhiana": [
    "BRS Nagar",
    "Civil Lines",
    "Dugri",
    "Ferozepur Road",
    "Ghumar Mandi",
    "Gill Road",
    "Haibowal",
    "Industrial Area A",
    "Industrial Area B",
    "Jamalpur",
    "Model Town",
    "Pakhowal Road",
    "Sarabha Nagar",
    "Shimlapuri",
    "Sunet"
  ],
  "Machillipatnam": [
    "Auto Nagar",
    "Bandar Road",
    "Guduru Road",
    "Koneru Centre",
    "Main Market Area",
    "Pedana Road",
    "Poleramma Temple Area"
  ],
  "Madurai": [
    "Anna Nagar",
    "Arapalayam",
    "Avaniyapuram",
    "Bypass Road",
    "Ellis Nagar",
    "KK Nagar",
    "Tallakulam",
    "Teppakulam",
    "Thirunagar",
    "Tirupparankundram",
    "Villapuram"
  ],
  "Mangalore": [
    "Balmatta",
    "Bejai",
    "Derebail",
    "Falnir",
    "Hampankatta",
    "Kadri",
    "Kankanady",
    "Kulai",
    "Panambur",
    "Surathkal",
    "Urwa"
  ],
  "Manipal": [
    "Ananth Nagar",
    "End Point Road",
    "Eshwar Nagar",
    "MIT Campus Area",
    "Madhav Nagar",
    "Tiger Circle Area",
    "Udupi Road Area"
  ],
  "Meerut": [
    "Civil Lines",
    "Defence Colony",
    "Ganga Nagar",
    "Garh Road",
    "Jagriti Vihar",
    "Kanker Khera",
    "Mawana Road",
    "Modipuram",
    "Pallavpuram",
    "Partapur",
    "Saket",
    "Shastri Nagar",
    "Shatabdi Nagar",
    "Surajkund"
  ],
  "Mohali": [
    "Sector 1",
    "Sector 10",
    "Sector 100",
    "Sector 101",
    "Sector 102",
    "Sector 103",
    "Sector 104",
    "Sector 105",
    "Sector 106",
    "Sector 107",
    "Sector 108",
    "Sector 109",
    "Sector 11",
    "Sector 110",
    "Sector 111",
    "Sector 112",
    "Sector 113",
    "Sector 114",
    "Sector 115",
    "Sector 116",
    "Sector 117",
    "Sector 118",
    "Sector 119",
    "Sector 12",
    "Sector 120",
    "Sector 121",
    "Sector 122",
    "Sector 123",
    "Sector 124",
    "Sector 125",
    "Sector 126",
    "Sector 127",
    "Sector 13",
    "Sector 14",
    "Sector 15",
    "Sector 16",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 2",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 29",
    "Sector 3",
    "Sector 30",
    "Sector 31",
    "Sector 32",
    "Sector 33",
    "Sector 34",
    "Sector 35",
    "Sector 36",
    "Sector 37",
    "Sector 38",
    "Sector 39",
    "Sector 4",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 44",
    "Sector 45",
    "Sector 46",
    "Sector 47",
    "Sector 48",
    "Sector 49",
    "Sector 5",
    "Sector 50",
    "Sector 51",
    "Sector 52",
    "Sector 53",
    "Sector 54",
    "Sector 55",
    "Sector 56",
    "Sector 57",
    "Sector 58",
    "Sector 59",
    "Sector 6",
    "Sector 60",
    "Sector 61",
    "Sector 62",
    "Sector 63",
    "Sector 64",
    "Sector 65",
    "Sector 66",
    "Sector 67",
    "Sector 68",
    "Sector 69",
    "Sector 7",
    "Sector 70",
    "Sector 71",
    "Sector 72",
    "Sector 73",
    "Sector 74",
    "Sector 75",
    "Sector 76",
    "Sector 77",
    "Sector 78",
    "Sector 79",
    "Sector 8",
    "Sector 80",
    "Sector 81",
    "Sector 82",
    "Sector 83",
    "Sector 84",
    "Sector 85",
    "Sector 86",
    "Sector 87",
    "Sector 88",
    "Sector 89",
    "Sector 9",
    "Sector 90",
    "Sector 91",
    "Sector 92",
    "Sector 93",
    "Sector 94",
    "Sector 95",
    "Sector 96",
    "Sector 97",
    "Sector 98",
    "Sector 99"
  ],
  "Moradabad": [
    "Budh Bazar",
    "Civil Lines",
    "Kanth Road",
    "Katghar",
    "Majhola",
    "Mughalpura",
    "Nawabpura",
    "Pakbara",
    "Ram Ganga Vihar"
  ],
  "Mumbai": [
    "Airoli",
    "Amboli",
    "Andheri",
    "Antop Hill",
    "Bandra",
    "Bhandup",
    "Bhayandar",
    "Borivali",
    "Byculla",
    "CBD Belapur",
    "Chembur",
    "Dadar",
    "Dahisar",
    "Dahisar East",
    "Dahisar West",
    "Dombivli East",
    "Dongri",
    "Ganesh Galli",
    "Garodia Nagar",
    "Ghatkopar",
    "Girgaon",
    "Goregaon",
    "Govandi",
    "Grant Road",
    "IC Colony",
    "J.B. Nagar",
    "Jogeshwari",
    "Kalina",
    "Kandivali",
    "Kanjurmarg",
    "Khar",
    "Kharghar",
    "Kurla",
    "Lower Parel",
    "Mahalaxmi",
    "Mahim",
    "Malad",
    "Marine Lines",
    "Matunga",
    "Mazagaon",
    "Mira Road",
    "Mulund",
    "Mumbra",
    "Nala Sopara",
    "Nariman Point",
    "Navi Mumbai",
    "Nerul",
    "Panvel",
    "Powai",
    "Sakinaka",
    "Sanpada",
    "Santacruz",
    "Santacruz East",
    "Santacruz West",
    "South Mumbai",
    "Thane",
    "Tilak Nagar",
    "Trombay",
    "Ulwe",
    "Vikhroli",
    "Vile Parle East",
    "Virar",
    "Wadala"
  ],
  "Mysuru": [
    "Alanahalli",
    "Bannimantap",
    "Bogadi",
    "Chamundipuram",
    "Gokulam",
    "Hebbal",
    "Hootagalli",
    "Jayalakshmipuram",
    "Kuvempunagar",
    "Lakshmipuram",
    "Saraswathipuram",
    "Siddhartha Layout",
    "Srirampura",
    "Vijayanagar",
    "Vontikoppal",
    "Yadavagiri"
  ],
  "Nadiad": [
    "College Road",
    "Mahagujarat Hospital Area",
    "Mission Road",
    "Nana Kumbhnath Road",
    "Pij Road",
    "Santram Road",
    "Vaniyavad"
  ],
  "Nagpur": [
    "Bajaj Nagar",
    "Civil Lines",
    "Dharampeth",
    "Hingna",
    "Itwari",
    "Jaripatka",
    "Kamptee Road",
    "Khamla",
    "Koradi Road",
    "Laxmi Nagar",
    "MIHAN",
    "Mahal",
    "Manish Nagar",
    "Mankapur",
    "Medical Square",
    "Nandanvan",
    "Narendra Nagar",
    "Pratap Nagar",
    "Ramdaspeth",
    "Sadar",
    "Shankar Nagar",
    "Sitabuldi",
    "Trimurti Nagar",
    "Umred Road",
    "Wardhaman Nagar"
  ],
  "Nanded": [
    "Anand Nagar",
    "CIDCO",
    "Degloor Naka",
    "Itwara",
    "Shivaji Nagar",
    "Taroda Naka",
    "Vazirabad",
    "Vishnupuri"
  ],
  "Narsipatnam": [
    "Chintapalli Road",
    "Gandhi Chowk",
    "Kotha Road Area",
    "Main Road Area",
    "RTC Complex Area"
  ],
  "Nashik": [
    "Canada Corner",
    "College Road",
    "Dwarka",
    "Gangapur Road",
    "Govind Nagar",
    "Indira Nagar",
    "Mhasrul",
    "Panchavati",
    "Pathardi Phata",
    "Satpur"
  ],
  "Nizamabad": [
    "Armoor Road",
    "Giriraj Nagar",
    "Khaleelwadi",
    "Mubarak Nagar",
    "Pragathi Nagar",
    "Vinayak Nagar",
    "Yellammagutta"
  ],
  "Noida": [
    "Sector 1",
    "Sector 10",
    "Sector 100",
    "Sector 101",
    "Sector 102",
    "Sector 103",
    "Sector 104",
    "Sector 105",
    "Sector 106",
    "Sector 107",
    "Sector 108",
    "Sector 109",
    "Sector 11",
    "Sector 110",
    "Sector 111",
    "Sector 112",
    "Sector 113",
    "Sector 114",
    "Sector 115",
    "Sector 116",
    "Sector 117",
    "Sector 118",
    "Sector 119",
    "Sector 12",
    "Sector 120",
    "Sector 121",
    "Sector 122",
    "Sector 123",
    "Sector 124",
    "Sector 125",
    "Sector 126",
    "Sector 127",
    "Sector 128",
    "Sector 129",
    "Sector 13",
    "Sector 130",
    "Sector 131",
    "Sector 132",
    "Sector 133",
    "Sector 134",
    "Sector 135",
    "Sector 136",
    "Sector 137",
    "Sector 138",
    "Sector 139",
    "Sector 14",
    "Sector 140",
    "Sector 140A",
    "Sector 141",
    "Sector 142",
    "Sector 143",
    "Sector 143A",
    "Sector 143B",
    "Sector 144",
    "Sector 145",
    "Sector 146",
    "Sector 147",
    "Sector 148",
    "Sector 149",
    "Sector 15",
    "Sector 150",
    "Sector 151",
    "Sector 152",
    "Sector 153",
    "Sector 154",
    "Sector 155",
    "Sector 156",
    "Sector 157",
    "Sector 158",
    "Sector 159",
    "Sector 16",
    "Sector 160",
    "Sector 161",
    "Sector 162",
    "Sector 163",
    "Sector 164",
    "Sector 165",
    "Sector 166",
    "Sector 167",
    "Sector 168",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 2",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 29",
    "Sector 3",
    "Sector 30",
    "Sector 31",
    "Sector 32",
    "Sector 33",
    "Sector 34",
    "Sector 35",
    "Sector 36",
    "Sector 37",
    "Sector 38",
    "Sector 39",
    "Sector 4",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 44",
    "Sector 45",
    "Sector 46",
    "Sector 47",
    "Sector 48",
    "Sector 49",
    "Sector 5",
    "Sector 50",
    "Sector 51",
    "Sector 52",
    "Sector 53",
    "Sector 54",
    "Sector 55",
    "Sector 56",
    "Sector 57",
    "Sector 58",
    "Sector 59",
    "Sector 6",
    "Sector 60",
    "Sector 61",
    "Sector 62",
    "Sector 63",
    "Sector 64",
    "Sector 65",
    "Sector 66",
    "Sector 67",
    "Sector 68",
    "Sector 69",
    "Sector 7",
    "Sector 70",
    "Sector 71",
    "Sector 72",
    "Sector 73",
    "Sector 74",
    "Sector 75",
    "Sector 76",
    "Sector 77",
    "Sector 78",
    "Sector 79",
    "Sector 8",
    "Sector 80",
    "Sector 81",
    "Sector 82",
    "Sector 83",
    "Sector 84",
    "Sector 85",
    "Sector 86",
    "Sector 87",
    "Sector 88",
    "Sector 89",
    "Sector 9",
    "Sector 90",
    "Sector 91",
    "Sector 92",
    "Sector 93",
    "Sector 94",
    "Sector 95",
    "Sector 96",
    "Sector 97",
    "Sector 98",
    "Sector 99"
  ],
  "Panchkula": [
    "Sector 1",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 12A",
    "Sector 13",
    "Sector 14",
    "Sector 15",
    "Sector 16",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 2",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 3",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Sector 7",
    "Sector 8",
    "Sector 9"
  ],
  "Panipat": [
    "Assandh Road",
    "GT Road Area",
    "HUDA Sector 11",
    "HUDA Sector 12",
    "Model Town",
    "Sanoli Road",
    "Tehsil Camp"
  ],
  "Pathankot": [
    "Dalhousie Road",
    "Improvement Trust Area",
    "Lamini",
    "Malikpur",
    "Mamoon Cantt",
    "Model Town"
  ],
  "Patiala": [
    "Bhadson Road",
    "Leela Bhawan",
    "Model Town",
    "Rajpura Road",
    "Tripuri",
    "Urban Estate Phase 1",
    "Urban Estate Phase 2"
  ],
  "Patna": [
    "AIIMS Patna Road",
    "Anandpuri",
    "Anisabad",
    "Ashiana Nagar",
    "Ashok Rajpath",
    "Bailey Road",
    "Bihta",
    "Boring Road",
    "Bypass Chowk",
    "Dak Bungalow Road",
    "Danapur",
    "Digha",
    "Exhibition Road",
    "Fraser Road",
    "Gola Road",
    "Gulzarbagh",
    "Jagdeo Path",
    "Kankarbagh",
    "Khagaul Road",
    "Kidwaipuri",
    "Kurji",
    "Mithapur",
    "Nehru Nagar",
    "New Patliputra Colony",
    "Pahleja Ghat",
    "Patliputra Colony",
    "Patna City",
    "Patna Sahib",
    "Phulwari Sharif",
    "Raja Bazar",
    "Rajendra Nagar",
    "Rajendranagar Terminal",
    "Rukanpura",
    "Saguna More",
    "Sheikhpura",
    "Shivpuri"
  ],
  "Pondicherry": [
    "Ariyankuppam",
    "Bahour",
    "Heritage Town",
    "Kalapet",
    "Lawspet",
    "Mudaliarpet",
    "Muthialpet",
    "Rainbow Nagar",
    "Reddiarpalayam",
    "White Town"
  ],
  "Allahabad": [
    "Allahpur",
    "Civil Lines",
    "Daraganj",
    "George Town",
    "Jhunsi",
    "Katra",
    "Mumfordganj",
    "Naini",
    "Rajapur",
    "Tagore Town"
  ],
  "Pune": [
    "Agarkar Nagar",
    "Akurdi",
    "Alandi",
    "Ambegaon Budruk",
    "Aundh",
    "Balewadi",
    "Baner",
    "Bavdhan",
    "Bhau Patil Road",
    "Bhosari",
    "Bhugaon",
    "Bhusari Colony",
    "Bibwewadi",
    "Bopodi",
    "Camp",
    "Chakan",
    "Chakan MIDC",
    "Chinchwad",
    "Chinchwadgaon",
    "Dange Chowk",
    "Dapodi",
    "Deccan Gymkhana",
    "Dhankawadi",
    "Dhanori",
    "Dhayari",
    "Dighi",
    "Erandwane",
    "Fatima Nagar",
    "Fursungi",
    "Gahunje",
    "Ganesh Peth",
    "Ganeshkhind",
    "Gangadham",
    "Ghorpadi",
    "Ghorpuri",
    "Gokhale Nagar",
    "Gultekdi",
    "Guru Nanak Nagar",
    "Hadapsar",
    "Handewadi Road",
    "Hinjawadi",
    "Indapur",
    "Indrayani Nagar",
    "JM Road",
    "Jagtap Dairy",
    "Jai Bhavani Nagar",
    "Jambhulwadi",
    "Janardannagar",
    "Kalyani Nagar",
    "Kamshet",
    "Karve Nagar",
    "Katraj",
    "Kedari Nagar",
    "Keshav Nagar",
    "Khadakwasla",
    "Khadki",
    "Khandala",
    "Kharadi",
    "Khondhwa",
    "Kothrud",
    "Kothrud(Pune)",
    "Lohegaon",
    "Lonavala",
    "Lonikand",
    "Lulla Nagar",
    "Magarpatta City",
    "Mahalunge",
    "Maharshi Nagar",
    "Mahatma Phule Peth",
    "Manjari",
    "Manjari Budruk",
    "Market Yard",
    "Marunji",
    "Mohammadwadi",
    "Moshi",
    "Mundhwa",
    "NIBM Road",
    "Nana Peth",
    "Nanded",
    "Nanded City",
    "Naneghat",
    "Narhe",
    "Navi Peth",
    "Navsahyadri",
    "Nehru Nagar",
    "Nigdi",
    "Old Mumbai Pune Highway",
    "Padmavati",
    "Pashan",
    "Pashan Sus Road",
    "Pimple Gurav",
    "Pimple Nilakh",
    "Pimple Saudagar",
    "Pimpri",
    "Pimpri Chinchwad",
    "Pirangut",
    "Pradhikaran",
    "Pulachi Wadi",
    "Rasta Peth",
    "Ravet",
    "Sadashiv Peth",
    "Sahakar Nagar",
    "Salisbury Park",
    "Sangamwadi",
    "Saswad",
    "Satara Road",
    "Shivajinagar",
    "Sinhagad Road",
    "Sus",
    "Sutarwadi",
    "Swargate",
    "Talawade",
    "Talegaon Dabhade",
    "Tathawade",
    "Thergaon",
    "Tingre Nagar",
    "Undri",
    "Uruli Devachi",
    "Vadgaon Budruk",
    "Vadgaon Sheri",
    "Viman Nagar",
    "Vishrantwadi",
    "Wadgaon Sheri",
    "Wagholi",
    "Wakad",
    "Wanwadi",
    "Warje",
    "Yerawada"
  ],
  "Raipur": [
    "Avanti Vihar",
    "Devendra Nagar",
    "Kota",
    "Mowa",
    "Pandri",
    "Samta Colony",
    "Shankar Nagar",
    "Tatibandh",
    "Telibandha",
    "VIP Road Area"
  ],
  "Rajkot": [
    "150 Feet Ring Road",
    "Gondal Road",
    "Kalawad Road",
    "Kotharia",
    "Madhapar",
    "Mavdi",
    "Nana Mava Road",
    "Race Course Road",
    "Raiya Road",
    "University Road"
  ],
  "Ranchi": [
    "Ashok Nagar",
    "Bariatu",
    "Booty More",
    "Doranda",
    "Harmu",
    "Kanke Road",
    "Lalpur",
    "Morabadi",
    "Namkum",
    "Upper Bazar"
  ],
  "Rourkela": [
    "Basanti Colony",
    "Bondamunda",
    "Chhend Colony",
    "Civil Township",
    "Fertilizer Township",
    "Koelnagar",
    "Panposh",
    "Sector 2",
    "Sector 5",
    "Udit Nagar"
  ],
  "Salem": [
    "Alagapuram",
    "Ammapet",
    "Fairlands",
    "Gugai",
    "Hasthampatti",
    "Meyyanur",
    "Shevapet",
    "Suramangalam",
    "Swarnapuri"
  ],
  "Siliguri": [
    "Ashrampara",
    "Bidhan Market Area",
    "Champasari",
    "Dagapur",
    "Hakimpara",
    "Matigara",
    "Pradhan Nagar",
    "Salugara",
    "Sevoke Road"
  ],
  "Sri Ganganagar": [
    "Civil Lines",
    "Jawahar Nagar",
    "Kesrisinghpur Road",
    "Padampur Road",
    "Riddhi Siddhi Enclave",
    "Shastri Nagar",
    "Suratgarh Road"
  ],
  "Srinagar": [
    "Batamaloo",
    "Bemina",
    "Hazratbal",
    "Jawahar Nagar",
    "Lal Chowk",
    "Nishat",
    "Rainawari",
    "Rajbagh",
    "Shalimar"
  ],
  "Surat": [
    "Adajan",
    "Althan",
    "Athwa",
    "Bhatar",
    "City Light",
    "Dumas Road",
    "Ghod Dod Road",
    "Hazira Road",
    "Katargam",
    "Limbayat",
    "Majura Gate",
    "Mota Varachha",
    "Nana Varachha",
    "Nanpura",
    "Pal",
    "Palanpur",
    "Pandesara",
    "Piplod",
    "Rander",
    "Sachin",
    "Udhna",
    "Varachha",
    "Vesu"
  ],
  "Thane": [
    "Balkum",
    "Ghodbunder Road",
    "Hiranandani Estate",
    "Kalwa",
    "Kasarvadavali",
    "Kolshet",
    "Kopri",
    "Lok Puram",
    "Majiwada",
    "Manpada",
    "Mumbra",
    "Naupada",
    "Owale",
    "Panchpakhadi",
    "Vartak Nagar",
    "Vasant Vihar",
    "Wagle Estate",
    "Yeoor Hills"
  ],
  "Thrissur": [
    "Ayyanthole",
    "East Fort",
    "Kuriachira",
    "Kuttur",
    "Mannuthy",
    "Ollur",
    "Poothole",
    "Punkunnam",
    "Vadakke Stand",
    "West Fort"
  ],
  "Trivandrum": [
    "Akkulam",
    "Alamcode",
    "Ambalamukku",
    "Ambalathara",
    "Anad",
    "Anayara",
    "Andoorkonam",
    "Arappuramukku",
    "Aruvikkara",
    "Aryanad",
    "Athiyannoor",
    "Attakulangara",
    "Attingal",
    "Ayiroopara",
    "Azhoor",
    "Balaramapuram",
    "Chacka",
    "Chalai",
    "Chanthavila",
    "Chempazhanthy",
    "Chenkal",
    "Chirayinkeezhu",
    "EastFort",
    "Gandhipuram",
    "Idapazhanji",
    "Jagathy",
    "JawaharNagar",
    "Kadakampally",
    "Kadinamkulam",
    "Kaithamukku",
    "Kalady",
    "Kallampally",
    "Kallara",
    "Kallayam",
    "Kallikad",
    "Kalliyoor",
    "Kaniyapuram",
    "Kanjiramkulam",
    "Karakulam",
    "Karamana",
    "Karipooru",
    "Karode",
    "Karumkulam",
    "Kattakada",
    "Kazhakkoottam",
    "Keezharoor",
    "Keezhthonakkal",
    "Kesavadasapuram",
    "Killipalam",
    "Kochulloor",
    "Kochuveli",
    "Kollayil",
    "Kottukal",
    "Kovalam",
    "Kowdiar",
    "Kudappanakunnu",
    "Kulasekharam",
    "Kulathoor",
    "Kulathummal",
    "Kundamankadavu",
    "Kunnathukal",
    "Kunnukuzhi",
    "Kuruppuzha",
    "Kuzhivila",
    "Malayinkeezhu",
    "Manacaud",
    "Manikkal",
    "Mannoorkara",
    "Manvila",
    "Marappalam",
    "Maruthumkuzhi",
    "Melthonnakkal",
    "Menamkulam",
    "Mudavanmugal",
    "Mukkolakkal",
    "Muttada",
    "Muttathara",
    "Nalanchira",
    "Nandavanam",
    "Navaikulam",
    "Nedumangadu",
    "Nemom",
    "Nettayam",
    "Neyyattinkara",
    "Njandoorkonam",
    "Oottukuzhy",
    "PMG",
    "Palayam",
    "Palkulangara",
    "Pallichal",
    "Pallickal",
    "Palode",
    "Panavoor",
    "Pangappara",
    "Pangode",
    "Pappanamcode",
    "Parasala",
    "Parasuvakkal",
    "Paruthippara",
    "Pattom",
    "Perinjamala",
    "Peroorkada",
    "Perumkadavila",
    "Perumkulam",
    "Perumpazhuthoor",
    "Pettah",
    "Poojapura",
    "Poovar",
    "Pothencode",
    "Powdikonam",
    "Pulayanarkotta",
    "Pulimoodu",
    "Pullampara",
    "Sasthamangalam",
    "Shangumukham",
    "SreeVaraham",
    "Sreekaryam",
    "Thekkada",
    "Thennoor",
    "Thirumala",
    "Thirupuram",
    "Thiruvallam",
    "Thiruvananthapuram",
    "Tholikkode",
    "Thonnakkal",
    "Thycaud",
    "Uliyazhathura",
    "Ulloor",
    "Uzhamalakkal",
    "Vakkom",
    "Valiyavila",
    "Vamanapuram",
    "Vanchiyoor",
    "Varkala",
    "Vattapara",
    "Vattiyoorkavu",
    "Vazhayila",
    "Vazhuthacaud",
    "Veeranakavu",
    "Veiloor",
    "Vellanad",
    "Vellayambalam",
    "Vellayani",
    "Vembayam",
    "Venganoor",
    "Vettamukku",
    "Vilappil",
    "Vithura",
    "Vizhinjam"
  ],
  "Tumakuru": [
    "Ashok Nagar",
    "Batawadi",
    "Gubbi Road",
    "Kuvempunagar",
    "Kyathsandra",
    "Maralur",
    "SS Puram",
    "Siddaganga Layout",
    "Ward 18 Area"
  ],
  "Udaipur": [
    "Fatehpura",
    "Hiran Magri",
    "Saheli Nagar",
    "Sector 14",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Shobhagpura",
    "Surajpole",
    "University Road"
  ],
  "Ujjain": [
    "Agar Road",
    "Dewas Road",
    "Freeganj",
    "Indore Road",
    "Jiwaji Ganj",
    "Mahakal Area",
    "Nanakheda",
    "Triveni Nagar",
    "Vasant Vihar"
  ],
  "Vadodara": [
    "Akota",
    "Alkapuri",
    "Fatehgunj",
    "Gotri",
    "Karelibaug",
    "Manjalpur",
    "Sama Savli Road",
    "Sayajigunj",
    "Subhanpura",
    "Vasna",
    "Waghodia Road"
  ],
  "Vellore": [
    "Bagayam",
    "Gandhi Nagar",
    "Katpadi",
    "Kosapet",
    "Saidapet",
    "Sathuvachari",
    "Thorapadi",
    "Viruthampattu"
  ],
  "Vijayawada": [
    "Ajit Singh Nagar",
    "Benz Circle",
    "Gollapudi",
    "Governorpet",
    "Kanuru",
    "Labbipet",
    "Moghalrajpuram",
    "Patamata",
    "Poranki"
  ],
  "Vizag": [
    "Akkayapalem",
    "Dwaraka Nagar",
    "Gajuwaka",
    "MVP Colony",
    "Madhurawada",
    "NAD Junction",
    "Pendurthi",
    "Rushikonda",
    "Seethammadhara"
  ],
  "Vizianagaram": [
    "Cantonment Area",
    "Collectorate Area",
    "Dasannapeta",
    "Dwarapudi Road",
    "Fort Area",
    "Phool Bagh",
    "RTC Complex Area"
  ],
  "Warangal": [
    "Chaitanyapuri",
    "Hanamkonda",
    "Kazipet",
    "Kothawada",
    "Madikonda",
    "Naim Nagar",
    "Subedari",
    "Waddepally"
  ],
  "Yamunanagar": [
    "Camp Area",
    "East Bhatia Nagar",
    "Jagadhri Road",
    "Model Town",
    "Sector 17",
    "West Bhatia Nagar",
    "Workshop Road"
  ],
  "Zirakpur": [
    "Ambala Highway",
    "Baltana",
    "Dhakoli",
    "Gazipur",
    "Kishanpura",
    "Lohgarh",
    "Nabha Sahib Road",
    "Patiala Road",
    "Peer Muchalla",
    "VIP Road"
  ]
};

export const TIME_PERIODS_DATA: Record<string, string[]> = {
    "Morning": ["06:00 AM", "06:30 AM", "07:00 AM", "07:30 AM", "08:00 AM", "08:30 AM", "09:00 AM", "09:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM"],
    "Afternoon": ["12:00 PM", "12:30 PM", "01:00 PM", "01:30 PM", "02:00 PM", "02:30 PM", "03:00 PM", "03:30 PM"],
    "Evening": ["04:00 PM", "04:30 PM", "05:00 PM", "05:30 PM", "06:00 PM", "06:30 PM", "07:00 PM", "07:30 PM", "08:00 PM", "08:30 PM", "09:00 PM"]
};

export const DAY_GROUPS_DATA = {
    "Weekdays": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    "Weekend": ["Saturday", "Sunday"]
};
